import json
with open("settings.json", "r") as json_file:
    data = json.load(json_file)

ELEVATOR_IMAGE = 'elv.png' 
FLOOR_BACKGROUND ='blocks.jpg'
ELEVATOR_IMAGE = 'elv.png'
DING_SOUND = 'ding.mp3'
TIME_ITERATION = 1 / 60
HEIGHT_SCREEN = 890
WIDTH_SCREEN = 800
LINE_HEIGHT = 7
HEIGHT_FLOOR = 60
WIDTH_FLOOR = 200
FONT_TIMER_TEXT = 28
CIRCLE_RADIUS = 20
HEIGHT_IMAGE_FLOOR = HEIGHT_FLOOR - LINE_HEIGHT
HEIGHT_ELEVATOR = 60
WIDTH_ELEVATOR = 60
DELAY_DURATION = 2.0
FLOOR_LENGTH_TIME = 0.5
BLOCK_SIZE_X = 55
BLOCK_SIZE_Y = 27
EXTRA_FLOOR = 1
UP = - 1
DOWN = 1
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0 , 255 , 0)
YELLOW = (255, 255, 0)
RED = (255, 0, 0)

