ELEVATOR_IMAGE = 'elv.png'
FLOOR_BACKGROUND ='blocks.jpg'
ELEVATOR_IMAGE = 'elv.png'
DING_SOUND = 'ding.mp3'

WIDTH_SCREEN = 800
HEIGHT_SCREEN = 630
LINE_HEIGHT = 7
HEIGHT_FLOOR = 70
WIDTH_FLOOR = 200
HEIGHT_ELEVATOR = 70
WIDTH_ELEVATOR = 60
SPEED_ELEVATOR = 5
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
